#!/bin/bash

# Компиляция исходников
# -sourcepath - указывает на зависимые модули в других пакетах
# -classpath - Необходимо прописать пути к используемым библиотекам
# -d ./bin - указывает на папку, где будут лежать скомпилированные классы

javac -sourcepath ./src -classpath ./lib/logback-core-1.1.9.jar:./lib/logback-classic-1.1.9.jar:./lib/slf4j-api-1.7.22.jar:./lib/slf4j-nop-1.7.22.jar -d bin ./src/edu/csf/oop/java/schedule/console/GlobalInterface.java

# Создание jar архива
# --create - создание архива
# --file - название архива
# --manifest - файл манифеста, в котором есть описание main класса и путей к скомпилированным выше файлам и либам
# -C - где лежат скомпилированные файлы
# . - путь, где создаем jar

# Запускается командой java -jar путь к архиву

jar --create --file schedule.jar --manifest manifest.mf -C ./bin/ .
